-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 11:58:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema velo_v1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema velo_v1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `velo_v1` DEFAULT CHARACTER SET utf8 ;
USE `velo_v1` ;

-- -----------------------------------------------------
-- Table `velo_v1`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `velo_v1`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(150) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `date_naissance` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(150) NOT NULL,
  `numero_telephone` VARCHAR(16) NOT NULL,
  `TypeUser_idTypeUser` INT NOT NULL,
  `CarteBleu_idCarteBleu` INT NOT NULL,
  `Panier_idPanier` INT NOT NULL,
  `ville_idAdress` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  INDEX `fk_User_TypeUser1_idx` (`TypeUser_idTypeUser` ASC),
  INDEX `fk_User_CarteBleu1_idx` (`CarteBleu_idCarteBleu` ASC),
  INDEX `fk_User_Panier1_idx` (`Panier_idPanier` ASC),
  INDEX `fk_User_ville1_idx` (`ville_idAdress` ASC),
  CONSTRAINT `fk_User_TypeUser1`
    FOREIGN KEY (`TypeUser_idTypeUser`)
    REFERENCES `velo_v1`.`TypeUser` (`idTypeUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_CarteBleu1`
    FOREIGN KEY (`CarteBleu_idCarteBleu`)
    REFERENCES `velo_v1`.`CarteBleu` (`idCarteBleu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Panier1`
    FOREIGN KEY (`Panier_idPanier`)
    REFERENCES `velo_v1`.`Panier` (`idPanier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_ville1`
    FOREIGN KEY (`ville_idAdress`)
    REFERENCES `velo_v1`.`adresse` (`idAdress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `velo_v1`.`TypeUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `velo_v1`.`TypeUser` (
  `idTypeUser` INT NOT NULL AUTO_INCREMENT,
  `Type_Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTypeUser`),
  UNIQUE INDEX `idType User_UNIQUE` (`idTypeUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `velo_v1`.`CarteBleu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `velo_v1`.`CarteBleu` (
  `idCarteBleu` INT NOT NULL AUTO_INCREMENT,
  `type_CB` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Date_Validite` VARCHAR(10) NOT NULL,
  `Active` INT(1) NULL,
  PRIMARY KEY (`idCarteBleu`),
  UNIQUE INDEX `idCarte Bleu_UNIQUE` (`idCarteBleu` ASC),
  UNIQUE INDEX `id CB CE_UNIQUE` (`type_CB` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `velo_v1`.`TVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `velo_v1`.`TVA` (
  `idTVA` INT NOT NULL AUTO_INCREMENT,
  `taux_TVA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTVA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `velo_v1`.`Forfait`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `velo_v1`.`Forfait` (
  `idForfait` INT NOT NULL AUTO_INCREMENT,
  `nom_Forfait` VARCHAR(45) NOT NULL,
  `type_Forfait` VARCHAR(45) NOT NULL,
  `duree_Forfait` VARCHAR(45) NOT NULL,
  `prix_Forfait` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idForfait`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `velo_v1`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `velo_v1`.`Article` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `nom_Article` VARCHAR(45) NOT NULL,
  `description_Article` VARCHAR(255) NOT NULL,
  `photo_Articla` VARCHAR(100) NOT NULL,
  `prix_unitair_Article` FLOAT NOT NULL,
  `Active` INT(1) NULL,
  `TVA_idTVA` INT NOT NULL,
  `Forfait_idForfait` INT NOT NULL,
  PRIMARY KEY (`idArticle`),
  INDEX `fk_Article_TVA1_idx` (`TVA_idTVA` ASC),
  INDEX `fk_Article_Forfait1_idx` (`Forfait_idForfait` ASC),
  CONSTRAINT `fk_Article_TVA1`
    FOREIGN KEY (`TVA_idTVA`)
    REFERENCES `velo_v1`.`TVA` (`idTVA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Article_Forfait1`
    FOREIGN KEY (`Forfait_idForfait`)
    REFERENCES `velo_v1`.`Forfait` (`idForfait`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `velo_v1`.`Panier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `velo_v1`.`Panier` (
  `idPanier` INT NOT NULL AUTO_INCREMENT,
  `qtite_Panier` VARCHAR(45) NOT NULL,
  `date_sorti_Panier` VARCHAR(45) NOT NULL,
  `date_entre_Panier` VARCHAR(45) NOT NULL,
  `Article_idArticle` INT NOT NULL,
  PRIMARY KEY (`idPanier`),
  INDEX `fk_Panier_Article1_idx` (`Article_idArticle` ASC),
  CONSTRAINT `fk_Panier_Article1`
    FOREIGN KEY (`Article_idArticle`)
    REFERENCES `velo_v1`.`Article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `velo_v1`.`adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `velo_v1`.`adresse` (
  `idAdress` INT NOT NULL AUTO_INCREMENT,
  `Adresse` VARCHAR(255) NOT NULL,
  `CP` VARCHAR(45) NOT NULL,
  `ville_nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `velo_v1`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `velo_v1`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(150) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `date_naissance` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(150) NOT NULL,
  `numero_telephone` VARCHAR(16) NOT NULL,
  `TypeUser_idTypeUser` INT NOT NULL,
  `CarteBleu_idCarteBleu` INT NOT NULL,
  `Panier_idPanier` INT NOT NULL,
  `ville_idAdress` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  INDEX `fk_User_TypeUser1_idx` (`TypeUser_idTypeUser` ASC),
  INDEX `fk_User_CarteBleu1_idx` (`CarteBleu_idCarteBleu` ASC),
  INDEX `fk_User_Panier1_idx` (`Panier_idPanier` ASC),
  INDEX `fk_User_ville1_idx` (`ville_idAdress` ASC),
  CONSTRAINT `fk_User_TypeUser1`
    FOREIGN KEY (`TypeUser_idTypeUser`)
    REFERENCES `velo_v1`.`TypeUser` (`idTypeUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_CarteBleu1`
    FOREIGN KEY (`CarteBleu_idCarteBleu`)
    REFERENCES `velo_v1`.`CarteBleu` (`idCarteBleu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Panier1`
    FOREIGN KEY (`Panier_idPanier`)
    REFERENCES `velo_v1`.`Panier` (`idPanier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_ville1`
    FOREIGN KEY (`ville_idAdress`)
    REFERENCES `velo_v1`.`adresse` (`idAdress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `velo_v1`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `velo_v1`.`Stock` (
  `idStock` INT NOT NULL AUTO_INCREMENT,
  `qtite_Stock` VARCHAR(45) NOT NULL,
  `dispo_Stock` INT NOT NULL,
  PRIMARY KEY (`idStock`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `velo_v1`.`Article_has_Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `velo_v1`.`Article_has_Stock` (
  `Article_idArticle` INT NOT NULL,
  `Stock_idStock` INT NOT NULL,
  PRIMARY KEY (`Article_idArticle`, `Stock_idStock`),
  INDEX `fk_Article_has_Stock_Stock1_idx` (`Stock_idStock` ASC),
  INDEX `fk_Article_has_Stock_Article1_idx` (`Article_idArticle` ASC),
  CONSTRAINT `fk_Article_has_Stock_Article1`
    FOREIGN KEY (`Article_idArticle`)
    REFERENCES `velo_v1`.`Article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Article_has_Stock_Stock1`
    FOREIGN KEY (`Stock_idStock`)
    REFERENCES `velo_v1`.`Stock` (`idStock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
